# Generated by Django 4.2.7 on 2024-01-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
