# Generated by Django 4.2.7 on 2024-01-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_course_review_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ratings',
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
