# Generated by Django 4.2.7 on 2024-01-30 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_lesson_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0006_remove_enrollment_course_alter_enrollment_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ManyToManyField(default=None, to='course.course'),
        ),
    ]
